### PR TITLE
fix: escape entities in attributes

### LINKED ISSUE #16: `innerSVG` does not escape < and > in attributes
### Describe the Bug

The `innerSVG(svg)` helper does not escape the attributes which leads to broken SVG.

### Steps to Reproduce

Cf. the test case in https://github.com/bpmn-io/tiny-svg/commit/83cd6a2ddc7b8b37f7fba30891dde394df0c308d

### Expected Behavior

The characters should be transformed into `&gt;` and `&lt;`.

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

---

Related to https://github.com/camunda/camunda-modeler/issues/4127

### PR DESCRIPTION
**Pull request by barmac**
Closes #16

### Proposed Changes

This makes sure we handle properly SVGs like `<g data-attr="&gt;" />`.

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [ ] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

File: test/spec/innerSVG.js [hunk 1]
```diff
@@ -218,6 +218,41 @@ describe('inner-svg', function() {
...
     });
 
+
+    it('should escape <> in attributes', function() {
+
+      // given
+      var container = createContainer();
+      var element = appendTo(create('svg'), container);
+
+      var text = '<g><rect data-foo="1 &lt; 2"/></g>';
```
Comment (nikku) [inline test/spec/innerSVG.js]:
```suggestion
      var text = '<g><rect data-foo="1 &lt;&gt; 2"/></g>';
```

Comment (barmac) [reply test/spec/innerSVG.js]: Sure

**Review by nikku — APPROVED** [review]

**Comment by barmac** [comment]
I will backport this to v3.x since we have not adopted v4 yet.
